// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnmDeliwWL_jpbiLGixOLXULnev7zuHOE',
    appId: '1:370802731084:web:3fc6b7a31d552b6a7eace9',
    messagingSenderId: '370802731084',
    projectId: 'swift-26949',
    authDomain: 'swift-26949.firebaseapp.com',
    storageBucket: 'swift-26949.firebasestorage.app',
    measurementId: 'G-1M4EW8CM09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoV6UvEYZUv6tmI4xseiaRt49iRP3LKX4',
    appId: '1:370802731084:android:19551b35d578c5817eace9',
    messagingSenderId: '370802731084',
    projectId: 'swift-26949',
    storageBucket: 'swift-26949.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeAul_PnVRgCLq1bdX6gL6JUz7TMuqe6U',
    appId: '1:370802731084:ios:b7e2434058c4b1c47eace9',
    messagingSenderId: '370802731084',
    projectId: 'swift-26949',
    storageBucket: 'swift-26949.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeAul_PnVRgCLq1bdX6gL6JUz7TMuqe6U',
    appId: '1:370802731084:ios:b7e2434058c4b1c47eace9',
    messagingSenderId: '370802731084',
    projectId: 'swift-26949',
    storageBucket: 'swift-26949.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnmDeliwWL_jpbiLGixOLXULnev7zuHOE',
    appId: '1:370802731084:web:29359ebd8cbe129c7eace9',
    messagingSenderId: '370802731084',
    projectId: 'swift-26949',
    authDomain: 'swift-26949.firebaseapp.com',
    storageBucket: 'swift-26949.firebasestorage.app',
    measurementId: 'G-54XS4Z1G9P',
  );
}
