// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUgQM4mCtGOkoC6P6akis3NoOWaRE6P3w',
    appId: '1:436918710355:web:088c2f897f2a31601f56a6',
    messagingSenderId: '436918710355',
    projectId: 'food-b56ae',
    authDomain: 'food-b56ae.firebaseapp.com',
    storageBucket: 'food-b56ae.appspot.com',
    measurementId: 'G-71MWFTZYD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZi2_aRiXnDboX_dBX0tznzheahqCA-lA',
    appId: '1:436918710355:android:c4e5d300eb75d46b1f56a6',
    messagingSenderId: '436918710355',
    projectId: 'food-b56ae',
    storageBucket: 'food-b56ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8z7p_NX8LbH4ECVMASBlBsMBWYPcbMTY',
    appId: '1:436918710355:ios:7e7a8408851fb12b1f56a6',
    messagingSenderId: '436918710355',
    projectId: 'food-b56ae',
    storageBucket: 'food-b56ae.appspot.com',
    iosBundleId: 'com.example.ytEcommerceAdminPanel',
  );
}
